'use client'

import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../components/navbar/navbar'
import { usePathname} from 'next/navigation'
import 'bootstrap-icons/font/bootstrap-icons.css';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const currentPath = usePathname();
  const showNavbar = (
    (currentPath === '/authentication/signin') || 
    (currentPath === '/authentication/signup') ||
    (currentPath === '/authentication/forgot-password')
    ) ? false : true;

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex h-screen flex-col'>
          {showNavbar && <Navbar />}
          {children}
        </div>
      </body>
    </html>
  )
}
